apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-nodejs
spec:
  params:
    - name: NODE_VERSION
      description: The ubi image to use for running the npm commands eg 'nodejs-12' or 'nodejs-10' etc
      type: string
      default: 'nodejs-10'
  results:
    - name: APP_VERSION
      description: the current app version as determined from the pacakge.json
  workspaces:
    - name: source
  steps:
    - name: set-app-version
      image: registry.access.redhat.com/ubi8/$(inputs.params.NODE_VERSION)
      workingDir: $(workspaces.source.path)
      script: |-
        echo -n "$(npm run version --silent)" > $(results.APP_VERSION.path)
        cat $(results.APP_VERSION.path)
        echo TODO ðŸ¦†ðŸ¦†ðŸ¦†
        printenv
    - name: install-deps
      image: registry.access.redhat.com/ubi8/$(inputs.params.NODE_VERSION)
      workingDir: $(workspaces.source.path)
      command: ['/bin/bash', '-c']
      args:
        - |-
          npm i
    - name: lint
      image: registry.access.redhat.com/ubi8/$(inputs.params.NODE_VERSION)
      workingDir: $(workspaces.source.path)
      command: ['/bin/bash', '-c']
      args:
        - |-
          npm run lint
    - name: test
      image: registry.access.redhat.com/ubi8/$(inputs.params.NODE_VERSION)
      workingDir: $(workspaces.source.path)
      command: ['/bin/bash', '-c']
      args:
        - |-
          npm run test:ci
    - name: build
      image: registry.access.redhat.com/ubi8/$(inputs.params.NODE_VERSION)
      workingDir: $(workspaces.source.path)
      command: ['/bin/bash', '-c']
      args:
        - |-
          npm run build
